openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  /updateChampion/{id}:
    put:
      tags:
      - champion-controller
      operationId: updateChampion
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ChampionUpdateRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ChampionResponse"
  /addChampion:
    post:
      tags:
      - champion-controller
      operationId: createChampion
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ChampionCreateRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ChampionResponse"
  /getChampions:
    get:
      tags:
      - champion-controller
      operationId: getChampions
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ChampionResponse"
  /getChampion/{id}:
    get:
      tags:
      - champion-controller
      operationId: getChampion
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ChampionResponse"
  /deleteChampion/{id}:
    delete:
      tags:
      - champion-controller
      operationId: deleteChampion
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
components:
  schemas:
    ChampionUpdateRequest:
      type: object
      properties:
        name:
          type: string
        role:
          type: string
        region:
          type: string
        type:
          type: string
        damage_type:
          type: string
    ChampionResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        role:
          type: string
        region:
          type: string
        damage_type:
          type: string
    ChampionCreateRequest:
      type: object
      properties:
        name:
          type: string
        role:
          type: string
        region:
          type: string
        type:
          type: string
        damage_type:
          type: string
